# netlify.toml
[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    "Access-Control-Allow-Origin" = "*"

[[headers]]
  for = "/*.js"
  [headers.values]
    "Content-Type" = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    "Content-Type" = "application/javascript; charset=utf-8"

[[headers]]
  for = "/chext_driver.js"
  [headers.values]
    "Content-Type" = "application/javascript; charset=utf-8"

[[headers]]
  for = "/chext_loader.js"
  [headers.values]
    "Content-Type" = "application/javascript; charset=utf-8"
